accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup', views.SignUp.as_view(), name = "signUp"),
    path('signin', views.SignIn.as_view(), name = "signIn"),
    path('signout', views.SignOut.as_view(), name = "signOut"),
    path('account', views.Profile.as_view(), name = "profile"),
]

blog/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name='blog'
urlpatterns = [
    path('', views.BlogView.as_view(), name='blog'),
    path('search', views.SearchView.as_view(), name='search'),
    path('<str:slug>/', views.DetailView.as_view(), name='d_blog'),
    path('user/subscribe/', views.SubscribeView.as_view(), name='subscribe'),
    path('add_comment/<str:pk>/', views.add_comment, name='add_comment'),
    path('add_reply/<str:pk>/<str:b_id>/', views.add_reply, name='add_reply'),
    path('ajax/up_vote/<str:pk>', views.up_vote, name='ajax_upvote'),
    path('ajax/down_vote/<str:pk>', views.down_vote, name='ajax_downvote'),
    ]

jobs/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView


app_name='jobs'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('forms/contact/', views.ContactView.as_view(), name='contact')
    ]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

admin.autodiscover()
admin.site.enable_nav_sidebar = False

handler404 = 'blog.views.error_404'

urlpatterns = [
    path('owner/', admin.site.urls),
    path('', include('jobs.urls')),
    path('blog/', include('blog.urls'), name='blog'),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path(r'^ckeditor/', include('ckeditor_uploader.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


jobs/models.py
from django.db import models

# Create your models here.


class Job(models.Model):
    title = models.CharField(max_length=200, null=True)
    description = models.TextField()
    company_name = models.CharField(max_length=50)
    date_from = models.DateField()
    date_to = models.DateField(null=True, blank=True)

    @property
    def description_bullet_points(self) -> list:
        return self.description.replace("\n", "").split("-")

    def __str__(self):
        return self.title

jobs/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.http import HttpResponse
from .models import Job
from django.core.mail import EmailMessage
from portfolio.settings import EMAIL_HOST_USER
from django.contrib import messages


class HomeView(View):
    def get(self, request):
        jobs = Job.objects.order_by('-date_from')
        return render(request, 'jobs/new_home.html', {"jobs":jobs})


class ContactView(View):
    def get(self, request):
        return HttpResponse("Method not allowed!")

    def post(self, request):
        name = request.POST.get('name')
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        message = request.POST.get('message')

        content = f"""
            Hello, it's {name},
            {message}
            
            Best,
            
            {name}
            {email} 
        """
        # send email

        try:
            email_body = content
            email = "yalchinmammadli@yalchin.info"

            msg = EmailMessage(
                subject,
                email_body,
                EMAIL_HOST_USER,
                [email]
            )
            msg.content_subtype = "html"
            msg.send()

            return HttpResponse("Your message has been sent successfully, thanks for reaching out!", status=200)

        except:
            return HttpResponse("", status=500)

jobs/templates/jobs/home.html
<!doctype html>
<html lang="en">
<head>
  {% load static %}
  <link rel="apple-touch-icon" href="/custom_icon.png"/>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Jekyll v4.1.1">
  <title>Yalchin Mammadli</title>

  <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/album/">

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <!-- Favicons -->
  <link rel="manifest" href="/docs/4.5/assets/img/favicons/manifest.json">
  <link rel="mask-icon" href="/docs/4.5/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c">
  <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
  <meta name="msapplication-config" content="/docs/4.5/assets/img/favicons/browserconfig.xml">
  <meta name="theme-color" content="#563d7c">

  <style>
  .bd-placeholder-img {
    font-size: 1.125rem;
    text-anchor: middle;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
  }

  @media (min-width: 768px) {
    .bd-placeholder-img-lg {
      font-size: 3.5rem;
    }
  }
  </style>
  <!-- Custom styles for this template -->
  <link href="" rel="stylesheet">
</head>
<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      {% if request.user.is_authenticated %}
          <a class="navbar-brand" href="{% url 'accounts:profile' %}">{{request.user.username.title}}</a>
      {% else %}
        <a class="navbar-brand" href="{% url 'jobs:home' %}">Yalchin Mammadli</a>
      {% endif %}
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
          {% if request.user.is_authenticated %}
          <a class="nav-link" href="{% url 'accounts:signOut' %}">Log Out</a>
          {% else %}
          <a class="nav-link" href="{% url 'accounts:signIn' %}">Log In</a>
          <a class="nav-link" href="{% url 'accounts:signUp' %}">Sign Up</a>
          {% endif %}
          <a class="nav-item nav-link" href="https://linkedin.com/in/yalchin-mammadli-42b30318a" target="_blank">Linkedin</a>
          <a class="nav-link" href="https://drive.google.com/drive/folders/1JKeq2t_Bf20ac_Mnd3bITwWqNFSWEtmf?usp=sharing" target="_blank">Certificates</a>
          <a class="nav-item nav-link" href="https://drive.google.com/drive/folders/1FN4CtQ_MhBuUi8FXbjKqqmmoxJLkZdCq?usp=sharing" target="_blank">Resume</a>
          <a class="nav-item nav-link" href="{% url 'blog:blog' %}">Blog</a>
        </div>
      </div>
    </nav>
  </header>

  <main role="main">

    <section class="jumbotron text-center">
      <div class="container">
        <h1>My portfolio and blog in one place!</h1>
        <p class="lead text-muted">Hi, there I'm a Self - Taught Developer, Linux Enthusiast, and Programming Tutor.I really enjoy working on web development, mainly server side. Here you can get more information about me and also enjoy the articles in blog section of website. Thank you for visiting!</p>
        <p>
          <a href="mailto:yalchinmammadli@yalchin.info" class="btn btn-primary my-2">E-mail me</a>
        </p>
        <img src="{% static "MY.jpg" %}" width="300" height="300">
      </div>
    </section>
<h1 class="text-center">Work Experience</h1><br>

    <div class="album py-5 bg-light">
      <div class="container">
        <div class="row">
          {% for job in jobs.all %}
          <div class="col-md-4">
            <div class="card mb-4 shadow-sm">
              <a href="{{ job.image.url }}"><img class="card-image-top" src="{{ job.image.url }}" width=100%></a>
              <div class="card-body">
                <h4>{{job.title}}</h4>
                <p class="card-text">{{ job.summary }}</p>

              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>

  </main>

  <footer class="text-muted">
    <div class="container text-center">
      <p> &copy; Yalchin Mammadli {% now "Y" %}</p>
    </div>
  </footer>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  <script>window.jQuery || document.write('<script src="/docs/4.5/assets/js/vendor/jquery.slim.min.js"><\/script>')</script><script src="" integrity="sha384-LtrjvnR4Twt/qOuYxE721u19sVFLVSA4hf/rRt6PrZTmiPltdZcI7q7PXQBYTKyf" crossorigin="anonymous"></script></body>
  <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-YZWT7RLV6H"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-YZWT7RLV6H');
</script>
</body>
  </html>